apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-pod-clusterip
  name: redis-cip
  namespace: test
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-pod
  type: ClusterIP
status:
  loadBalancer: {}